name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up CMake & Build
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential doxygen graphviz
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
