name: Manual GPTP Test on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-gptp:
    name: Run GPTP Test on i210 Windows Host
    runs-on: [self-hosted, windows, i210]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Verify WpdPack structure and env
      run: |
        echo "WPCAP_DIR is: $env:WPCAP_DIR"
        #dir "C:\WpdPack"
        #dir "C:\WpdPack\Include"
        #dir "C:\WpdPack\Lib"
      shell: powershell

    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Check that gptp.exe was created
      run: |
          $gptpExe = Get-ChildItem -Recurse -Filter gptp.exe | Select-Object -First 1
          
          if (-not $gptpExe) {
              Write-Error "❌ gptp.exe not found after build"
              exit 1
          } else {
              Write-Host "✅ Found: $($gptpExe.FullName)"
          }
      shell: powershell

    - name: Run gptp.exe with timeout
      shell: pwsh
      run: |
        $exe = Get-ChildItem -Recurse -Filter gptp.exe | Select-Object -First 1
        $process = Start-Process -FilePath $exe.FullName -ArgumentList "68-05-CA-8B-76-4E" -PassThru
        $timeoutSeconds = 30
    
        if (-not $process.WaitForExit($timeoutSeconds * 1000)) {
          Write-Host "Timeout reached. Killing gptp.exe"
          $process | Stop-Process -Force
          throw "gptp.exe did not exit within $timeoutSeconds seconds."
        } else {
          Write-Host "gptp.exe exited successfully."
        }
    
    - name: Run gptp.exe
      run: |
        $exe = Get-ChildItem -Recurse -Filter gptp.exe | Select-Object -First 1
        & $exe.FullName "68-05-CA-8B-76-4E"
      shell: powershell

